# Generated by Django 4.2.3 on 2023-08-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
