# Generated by Django 4.2.3 on 2023-08-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
