# Generated by Django 4.2.3 on 2023-08-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_product_price_id',
            new_name='stripe_products_price_id',
        ),
    ]
